name: Discord Release Webhook

on:
  release:
    types: 
      - published  # Triggers on both release and pre-release

jobs:
  send-webhook:
    runs-on: ubuntu-latest
    steps:
    - name: Send Webhook to Discord
      env:
        DISCORD_WEBHOOK_URL: ${{ secrets.DISCORD_WEBHOOK_URL }}  # Store this as a GitHub secret
      run: |
        curl -X POST -H "Content-Type: application/json" \
          -d "{\"content\": \"New release: **${{ github.event.release.name }}**\nTag: **${{ github.event.release.tag_name }}**\n${{ github.event.release.html_url }}\"}" \
          $DISCORD_WEBHOOK_URL
