name: Discord Release Webhook

on:
  release:
    types: 
      - published  # Triggers on both release and pre-release

jobs:
  send-webhook:
    runs-on: ubuntu-latest
    steps:
    - name: Send Webhook to Discord
      env:
        DISCORD_WEBHOOK_URL: ${{ secrets.DISCORD_WEBHOOK_URL }}  # Store this as a GitHub secret
      run: |
        # Check if it's a pre-release or full release
        if [ "${{ github.event.release.prerelease }}" = "true" ]; then
          RELEASE_TYPE="**Pre-release**"
        else
          RELEASE_TYPE="**Release**"
        fi

        # Format the date in ISO 8601
        RELEASE_DATE=$(date -d "${{ github.event.release.published_at }}" +%Y-%m-%dT%H:%M:%SZ)

        # Escape release body
        BODY=$(echo "${{ github.event.release.body }}" | jq -Rsa .)

        # Prepare the JSON payload
        PAYLOAD=$(jq -n \
          --arg content "${RELEASE_TYPE} Published by **${{ github.event.release.author.login }}**\n\n**Release Name**: ${{ github.event.release.name }}\n**Tag**: ${{ github.event.release.tag_name }}\n**Published at**: ${RELEASE_DATE}\n\n**Description**: ${BODY}\n\n[Release Link](${{ github.event.release.html_url }})" \
          '{content: $content}')

        # Debugging output (optional)
        echo "Sending payload: $PAYLOAD"

        # Send the webhook
        curl -X POST -H "Content-Type: application/json" -d "$PAYLOAD" $DISCORD_WEBHOOK_URL
